steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudbuild-demo:latest', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/cloudbuild-demo:latest']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'cloudbuild-demo'
   - '--image'
   - 'gcr.io/$PROJECT_ID/cloudbuild-demo:latest'
   - '--region'
   - 'australia-southeast1'
   - '--allow-unauthenticated'
   - '--port=80'
images:
  - 'gcr.io/$PROJECT_ID/cloudbuild-demo:latest'
